ALTER TABLE users ADD COLUMN first_name VARCHAR;
ALTER TABLE users ADD COLUMN last_name VARCHAR;
ALTER TABLE users ADD COLUMN name VARCHAR;
ALTER TABLE users ADD COLUMN initials VARCHAR(3);
ALTER TABLE users ADD COLUMN profile_picture VARCHAR;
