/* tslint:disable */
/* eslint-disable */
/**
 * Origin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MachineCreate
 */
export interface MachineCreate {
    /**
     * 
     * @type {string}
     * @memberof MachineCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MachineCreate
     */
    secret: string;
}

/**
 * Check if a given object implements the MachineCreate interface.
 */
export function instanceOfMachineCreate(value: object): value is MachineCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function MachineCreateFromJSON(json: any): MachineCreate {
    return MachineCreateFromJSONTyped(json, false);
}

export function MachineCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'secret': json['secret'],
    };
}

export function MachineCreateToJSON(json: any): MachineCreate {
    return MachineCreateToJSONTyped(json, false);
}

export function MachineCreateToJSONTyped(value?: MachineCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'secret': value['secret'],
    };
}

