/* tslint:disable */
/* eslint-disable */
/**
 * Origin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordUpdate
 */
export interface PasswordUpdate {
    /**
     * 
     * @type {string}
     * @memberof PasswordUpdate
     */
    password: string;
}

/**
 * Check if a given object implements the PasswordUpdate interface.
 */
export function instanceOfPasswordUpdate(value: object): value is PasswordUpdate {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function PasswordUpdateFromJSON(json: any): PasswordUpdate {
    return PasswordUpdateFromJSONTyped(json, false);
}

export function PasswordUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function PasswordUpdateToJSON(json: any): PasswordUpdate {
    return PasswordUpdateToJSONTyped(json, false);
}

export function PasswordUpdateToJSONTyped(value?: PasswordUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

