/* tslint:disable */
/* eslint-disable */
/**
 * Origin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Machine } from './Machine';
import {
    MachineFromJSON,
    MachineFromJSONTyped,
    MachineToJSON,
    MachineToJSONTyped,
} from './Machine';

/**
 * 
 * @export
 * @interface Score
 */
export interface Score {
    /**
     * 
     * @type {string}
     * @memberof Score
     */
    game: string;
    /**
     * 
     * @type {number}
     * @memberof Score
     */
    value: number;
    /**
     * 
     * @type {number}
     * @memberof Score
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Score
     */
    createdAt: Date;
    /**
     * 
     * @type {User}
     * @memberof Score
     */
    user: User;
    /**
     * 
     * @type {Machine}
     * @memberof Score
     */
    machine: Machine;
}

/**
 * Check if a given object implements the Score interface.
 */
export function instanceOfScore(value: object): value is Score {
    if (!('game' in value) || value['game'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('machine' in value) || value['machine'] === undefined) return false;
    return true;
}

export function ScoreFromJSON(json: any): Score {
    return ScoreFromJSONTyped(json, false);
}

export function ScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): Score {
    if (json == null) {
        return json;
    }
    return {
        
        'game': json['game'],
        'value': json['value'],
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'user': UserFromJSON(json['user']),
        'machine': MachineFromJSON(json['machine']),
    };
}

export function ScoreToJSON(json: any): Score {
    return ScoreToJSONTyped(json, false);
}

export function ScoreToJSONTyped(value?: Score | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'game': value['game'],
        'value': value['value'],
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'user': UserToJSON(value['user']),
        'machine': MachineToJSON(value['machine']),
    };
}

