/* tslint:disable */
/* eslint-disable */
/**
 * Origin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScoreCreate
 */
export interface ScoreCreate {
    /**
     * 
     * @type {string}
     * @memberof ScoreCreate
     */
    game: string;
    /**
     * 
     * @type {number}
     * @memberof ScoreCreate
     */
    value: number;
    /**
     * 
     * @type {number}
     * @memberof ScoreCreate
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof ScoreCreate
     */
    machineId: number;
}

/**
 * Check if a given object implements the ScoreCreate interface.
 */
export function instanceOfScoreCreate(value: object): value is ScoreCreate {
    if (!('game' in value) || value['game'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('machineId' in value) || value['machineId'] === undefined) return false;
    return true;
}

export function ScoreCreateFromJSON(json: any): ScoreCreate {
    return ScoreCreateFromJSONTyped(json, false);
}

export function ScoreCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'game': json['game'],
        'value': json['value'],
        'userId': json['user_id'],
        'machineId': json['machine_id'],
    };
}

export function ScoreCreateToJSON(json: any): ScoreCreate {
    return ScoreCreateToJSONTyped(json, false);
}

export function ScoreCreateToJSONTyped(value?: ScoreCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'game': value['game'],
        'value': value['value'],
        'user_id': value['userId'],
        'machine_id': value['machineId'],
    };
}

