/* tslint:disable */
/* eslint-disable */
/**
 * Origin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface ScoreOut
 */
export interface ScoreOut {
    /**
     * 
     * @type {number}
     * @memberof ScoreOut
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ScoreOut
     */
    value: number;
    /**
     * 
     * @type {Date}
     * @memberof ScoreOut
     */
    createdAt: Date;
    /**
     * 
     * @type {User}
     * @memberof ScoreOut
     */
    user: User;
}

/**
 * Check if a given object implements the ScoreOut interface.
 */
export function instanceOfScoreOut(value: object): value is ScoreOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function ScoreOutFromJSON(json: any): ScoreOut {
    return ScoreOutFromJSONTyped(json, false);
}

export function ScoreOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'value': json['value'],
        'createdAt': (new Date(json['created_at'])),
        'user': UserFromJSON(json['user']),
    };
}

export function ScoreOutToJSON(json: any): ScoreOut {
    return ScoreOutToJSONTyped(json, false);
}

export function ScoreOutToJSONTyped(value?: ScoreOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'value': value['value'],
        'created_at': ((value['createdAt']).toISOString()),
        'user': UserToJSON(value['user']),
    };
}

