/* tslint:disable */
/* eslint-disable */
/**
 * Origin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Machine,
  MachineCreate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MachineFromJSON,
    MachineToJSON,
    MachineCreateFromJSON,
    MachineCreateToJSON,
} from '../models/index';

export interface RegisterMachineApiV1MachinesPostRequest {
    machineCreate: MachineCreate;
}

/**
 * 
 */
export class MachinesApi extends runtime.BaseAPI {

    /**
     * Register Machine
     */
    async registerMachineApiV1MachinesPostRaw(requestParameters: RegisterMachineApiV1MachinesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Machine>> {
        if (requestParameters['machineCreate'] == null) {
            throw new runtime.RequiredError(
                'machineCreate',
                'Required parameter "machineCreate" was null or undefined when calling registerMachineApiV1MachinesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/machines/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MachineCreateToJSON(requestParameters['machineCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MachineFromJSON(jsonValue));
    }

    /**
     * Register Machine
     */
    async registerMachineApiV1MachinesPost(requestParameters: RegisterMachineApiV1MachinesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Machine> {
        const response = await this.registerMachineApiV1MachinesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
