/* tslint:disable */
/* eslint-disable */
/**
 * Origin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Score,
  ScoreCreate,
  ScoreOut,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ScoreFromJSON,
    ScoreToJSON,
    ScoreCreateFromJSON,
    ScoreCreateToJSON,
    ScoreOutFromJSON,
    ScoreOutToJSON,
} from '../models/index';

export interface GetTopScoresApiV1ScoresTopGameGetRequest {
    game: string;
    limit?: number;
    offset?: number;
}

export interface GetUserScoresApiV1ScoresUserUserIdGetRequest {
    userId: number;
    game?: string | null;
    limit?: number;
    offset?: number;
    top?: boolean;
}

export interface SubmitScoreApiV1ScoresPostRequest {
    scoreCreate: ScoreCreate;
}

/**
 * 
 */
export class ScoresApi extends runtime.BaseAPI {

    /**
     * Get Top Scores
     */
    async getTopScoresApiV1ScoresTopGameGetRaw(requestParameters: GetTopScoresApiV1ScoresTopGameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScoreOut>>> {
        if (requestParameters['game'] == null) {
            throw new runtime.RequiredError(
                'game',
                'Required parameter "game" was null or undefined when calling getTopScoresApiV1ScoresTopGameGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/scores/top/{game}`;
        urlPath = urlPath.replace(`{${"game"}}`, encodeURIComponent(String(requestParameters['game'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScoreOutFromJSON));
    }

    /**
     * Get Top Scores
     */
    async getTopScoresApiV1ScoresTopGameGet(requestParameters: GetTopScoresApiV1ScoresTopGameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScoreOut>> {
        const response = await this.getTopScoresApiV1ScoresTopGameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get User Scores
     */
    async getUserScoresApiV1ScoresUserUserIdGetRaw(requestParameters: GetUserScoresApiV1ScoresUserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScoreOut>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserScoresApiV1ScoresUserUserIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['game'] != null) {
            queryParameters['game'] = requestParameters['game'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['top'] != null) {
            queryParameters['top'] = requestParameters['top'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/scores/user/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScoreOutFromJSON));
    }

    /**
     * Get User Scores
     */
    async getUserScoresApiV1ScoresUserUserIdGet(requestParameters: GetUserScoresApiV1ScoresUserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScoreOut>> {
        const response = await this.getUserScoresApiV1ScoresUserUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit Score
     */
    async submitScoreApiV1ScoresPostRaw(requestParameters: SubmitScoreApiV1ScoresPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Score>> {
        if (requestParameters['scoreCreate'] == null) {
            throw new runtime.RequiredError(
                'scoreCreate',
                'Required parameter "scoreCreate" was null or undefined when calling submitScoreApiV1ScoresPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/api/v1/scores/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScoreCreateToJSON(requestParameters['scoreCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScoreFromJSON(jsonValue));
    }

    /**
     * Submit Score
     */
    async submitScoreApiV1ScoresPost(requestParameters: SubmitScoreApiV1ScoresPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Score> {
        const response = await this.submitScoreApiV1ScoresPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
